// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvQN3U74Qn3cVu_ehsiN4ekmaCeaJ2o1M',
    appId: '1:389070802659:android:defe1f6079d32ed134bfd6',
    messagingSenderId: '389070802659',
    projectId: 'wqfashion-98f4b',
    storageBucket: 'wqfashion-98f4b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAB7QhUxjavq5sB1evV_An2yyScb5Xsx9s',
    appId: '1:389070802659:ios:24827dd0848ec53f34bfd6',
    messagingSenderId: '389070802659',
    projectId: 'wqfashion-98f4b',
    storageBucket: 'wqfashion-98f4b.firebasestorage.app',
    androidClientId: '389070802659-t99447kqvjs8t5arphh5a1fintoqr6ut.apps.googleusercontent.com',
    iosClientId: '389070802659-1kbii44826q7hrco3icoeiofi2pq24as.apps.googleusercontent.com',
    iosBundleId: 'com.example.levisStore',
  );

}